### ISSUE TITLE
Коды перестали отображаться

### ISSUE THREAD

**Issue by RazgovovEvgen22** [alezhu/rshb_online_mcc#1]
Добрый день, ранее Вы сделали хорошую программу для отображение MCC кодов в онлайн банке Россельхозбанка, но Россельхозбанк что то обновил на сайте, и теперь коды не отображаются, если есть такая возможность можете сделать, что бы коды опять отображались. Проверял в Гугл браузере, Яндекс браузере и Файрфокс. Спасибо.

**Comment by alezhu** [comment]
Я в данный момент не пользуюсь картами росколхоза. Соответственно, ничем не могу помочь
